added problems
freeuni-paradigms/freeuni-paradigms.github.io pull request #31
Opened 2020-11-05 19:24 UTC by bes01

@glekveishvili

2020-11-11 09:27 UTC, glekveishvili requested changes
ამას გადახედე და ვეცადოთ ეს სტილი დავიცვათ: https://google.github.io/styleguide/cppguide.html

მაგალითად მე რაც შევამჩნიე:
1) ცვლადის სახელები პატარა ასეობით და _ აღწერე მაგალითად is_same
2) იგივე დირექტორიებზე და ფაილებზეც: good_students
3) ამოხსნის ფაილებს უბრალოდ solution.c -ს დავარქმევდი

2020-11-11 09:27 UTC, glekveishvili commented on exercises/extra/GoodStudents/GoodStudents.h
> +#include <unistd.h>
ეს ინკლუდები შეგვიძლია ამოვაგდოთ

2020-11-11 09:27 UTC, glekveishvili commented on exercises/extra/GoodStudents/GoodStudents_Solution.c
> +            answer[i++] = student;
ამოცანა ისე ხომ არ გადავაკეთოთ რომ სტუდენტების სახელების მასივის დაბრუნების მაგივრად მოვთხოვოთ ერთი სტრიქონის დაბრუნება სადაც სფეისებით იქნება სახელები გამოყოფილი და ბოლოში ეწერება \0 ?

2020-11-11 09:27 UTC, glekveishvili commented on exercises/extra/GoodStudents/GoodStudents_Solution.c
> +            answer[i++] = student;
memcpy-ს გამოყენებაც რომ მოუწიოს მაგისთვის

2020-11-11 09:27 UTC, glekveishvili commented on exercises/extra/GoodStudents/tests.c
> +    *((char*)ptr + strlen(nika) + 2 + strlen(luka) + 2 + strlen(kosta) + 2) = '\0';
ცოტა რთული გასაგებია ტესტი. ასეთი დამხმარე ფუნქცია რომ გვქონდეს:
void AddStudent(char* name, int* score, char** students)
რომელიც students-ის მიერ მითითებულ სტრიქონს realloc-ს გაუკეთებს და ბოლოში ახალ სტუდენტს მიაბამს.
მერე შეგეძლება გამოიყენო როგორც:
char* students = "";
AddStudent("Nika", 156, &students);
AddStudent("Luka", 149, &students);
...

2020-11-11 09:27 UTC, glekveishvili commented on exercises/extra/SuffixAndPrefix/SuffixAndPrefix_Solution.c
> +        char* answer = malloc(sizeof(char) * (strlen(str) - 2*N + 1));
2*N >= რომ იყოს strlen(str)-ზე ?

2020-11-11 09:27 UTC, glekveishvili commented on exercises/extra/SuffixAndPrefix/SuffixAndPrefix_Solution.c
> +        char* answer = malloc(sizeof(char) * (strlen(str) - 2*N + 1));
ტესტიც გვინდა ასეთი სავარაუდოდ

2020-11-11 09:27 UTC, glekveishvili commented on exercises/extra/SuffixAndPrefix/tests.c
> +    bool answer = strcmp(SuffAndPreff(strdup("aba"), 1), strdup("b")) == 0;
strdup-ებს რატომ იყენებ აქ და ქვემოთ?
თან არავინ არ ათავისუფლებს მაგ მეხსიერებებს.

2020-11-11 09:54 UTC, bes01 commented on exercises/extra/GoodStudents/GoodStudents_Solution.c
> +            answer[i++] = student;
კი, ჯობია, საღამოს გადავაკეთებ შენიშვნების მიხედვით.

2020-11-11 09:55 UTC, bes01 commented on exercises/extra/SuffixAndPrefix/SuffixAndPrefix_Solution.c
> +        char* answer = malloc(sizeof(char) * (strlen(str) - 2*N + 1));
მაგდროს არაფერი არუნდა იცვლებოდეს? მქონდა ეგეთი ტესტი და ამოვაგდე მერე...

2020-11-28 10:52 UTC, glekveishvili commented on exercises/extra/SuffixAndPrefix/SuffixAndPrefix_Solution.c
> +        char* answer = malloc(sizeof(char) * (strlen(str) - 2*N + 1));
მოდი მაგ დროს მთელი სტრიქონის გაცარიელება მოვთხოვოთ.

2020-11-28 10:54 UTC, glekveishvili approved these changes
კარგია, სულ ორი კომენტარი მაქვს. მაგათ რომ გაასწორებ შეგიძლია დამერჯო

2020-11-28 10:54 UTC, glekveishvili commented on exercises/extra/good_students/tests.c
> +void* addStudent(char* student, unsigned char score, void* address, size_t* address_length){
AddStudent

2020-11-28 18:21 UTC, bes01 commented on exercises/extra/SuffixAndPrefix/SuffixAndPrefix_Solution.c
> +        char* answer = malloc(sizeof(char) * (strlen(str) - 2*N + 1));
ეგ პირობაში დავამატო? თუ ნახევარზე დიდია ენითქო ცარიელი სტრიქონი დააბრუნეთ?

2020-11-28 18:26 UTC, bes01 commented on exercises/extra/SuffixAndPrefix/SuffixAndPrefix_Solution.c
> +        char* answer = malloc(sizeof(char) * (strlen(str) - 2*N + 1));
ალბათ, უნდა დავამატო;დ

2020-11-28 18:31 UTC, merged